WebApp/Controllers/HoaDonController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Shop_Models.Dto;
using Shop_Models.Entities;
using System.Net.Http;

namespace WebApp.Controllers
{
    public class HoaDonController : Controller
    {
        private readonly ILogger<HoaDonController> _logger;
        private readonly IConfiguration _config;
        private readonly IHttpClientFactory _httpClientFactory;

        public HoaDonController(ILogger<HoaDonController> logger, IConfiguration config, IHttpClientFactory httpClientFactory)
        {
            _logger = logger;
            _config = config;
            _httpClientFactory = httpClientFactory;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> ShowBill(string? invoiceCode)
        {

            try
            {

                using (var client = _httpClientFactory.CreateClient("BeHat"))
                {
                    HttpResponseMessage response = await client.GetAsync($"/PGetBillByInvoiceCode?invoiceCode={invoiceCode}");

                    if (response.IsSuccessStatusCode)
                    {
                        var resultString = await response.Content.ReadAsStringAsync();
                        var resultResponse = JsonConvert.DeserializeObject<ResponseDto>(resultString);
                        var billS = JsonConvert.DeserializeObject<HoaDonDto>(resultResponse.Content.ToString());
                        if (billS != null)
                        {
                            ViewBag.Bill = billS;
                            ViewBag.ListBillItem = billS.BillDetail;
                        }
                        else
                        {
                            ViewBag.ListBillItem = null;
                        }
                    }
                    else
                    {
                        ViewBag.ListBillItem = null;
                    }
                    return View();
                }

            }
            catch (Exception)
            {

                return View("Error");
            }
        }
        public async Task<ActionResult<List<HoaDon>>> GetCustomerPurchaseHistory(string customerId)
        {
            // Tạo một HTTP client từ factory
            var client = _httpClientFactory.CreateClient();

            // Gọi endpoint của controller MVC
            var response = await client.GetAsync($"https://localhost:7050/GetPurchaseHistory?customerId={customerId}");

            if (response.IsSuccessStatusCode)
            {
                var purchaseHistory = await response.Content.ReadAsStringAsync(); // Sử dụng phương thức mở rộng ReadFromJsonAsync()

                var jsondata = JsonConvert.DeserializeObject<List<HoaDon>>(purchaseHistory.ToString());
                return View(jsondata);
            }
            else
            {
                return StatusCode((int)response.StatusCode, "Không thể lấy dữ liệu lịch sử mua hàng.");
            }
        }
    }
}

WebApp/Views/HoaDon/GetCustomerPurchaseHistory.cshtml
@using static Shop_Models.Heplers.TrangThai;
@model IEnumerable<Shop_Models.Entities.HoaDon>

@{
    ViewData["Title"] = "GetCustomerPurchaseHistory";
}
<style>
    .table-container {
    border: 2px solid #ccc; /* Đường viền xung quanh khung */
    padding: 20px; /* Đệm trong khung */
    border-radius: 8px; /* Bo góc khung */
    margin: 20px; /* Khoảng cách bên ngoài khung */
    background-color: #f9f9f9; /* Màu nền khung */
}

.table {
    width: 100%; /* Chiếm toàn bộ chiều rộng khung */
    border-collapse: collapse; /* Gộp các đường viền bảng lại */
}

.table th {
    background-color: #f2f2f2; /* Màu nền tiêu đề bảng */
    font-weight: bold; /* Chữ đậm cho tiêu đề bảng */
}

</style>

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
	<div class="container">
		<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
			<div class="col-first">
				<h1>Tra Cứu Đơn Hàng</h1>
				<nav class="d-flex align-items-center">
					<a href="/Home">Home<span class="lnr lnr-arrow-right"></span></a>
					<a href="/HoaDon/ShowBill">Tra Cứu Đơn Hàng</a>
				</nav>
			</div>
		</div>
	</div>
</section>
<!-- End Banner Area -->
<br />
<h2 style="margin-left: 50px;">Lịch Sử Mua Hàng</h2>

<div id="hoaDonContainer" class="table-container">
    @if (Model != null && Model.Count() > 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Mã Hóa Đơn</th>
                    <th>Ngày Tạo</th>
                    <th>Ngày Thanh Toán</th>
                    <th>Ngày Ship</th>
                    <th>Ngày Nhận</th>
                    <th>Mô Tả</th>
                    <th>Tiền Giảm</th>
                    <th>Tiền Ship</th>
                    <th>Tổng Tiền</th>
                    <th>Trạng Thái Thanh Toán</th>
                    <th>Trạng Thái Giao Hàng</th>
                    <th>Lí Do Hủy</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var hoaDon in Model)
                {
                    <tr>
                        <td>@hoaDon.MaHoaDon</td>
                        <td>@hoaDon.NgayTao</td>
                        <td>@hoaDon.NgayThanhToan</td>
                        <td>@hoaDon.NgayShip</td>
                        <td>@hoaDon.NgayNhan</td>
                        <td>@hoaDon.MoTa</td>
                        <td>@hoaDon.TienGiam</td>
                        <td>@hoaDon.TienShip</td>
                        <td>@hoaDon.TongTien</td>
                        <td>
                            @if (@hoaDon.TrangThaiThanhToan == (int)TrangThaiThanhToan.Chuathanhtoan)
                            {
                                <span class="text-black">
                                     Chưa Thanh Toán
                                </span>
                            }
                            else if (@hoaDon.TrangThaiThanhToan == (int)TrangThaiThanhToan.Dathanhtoan)
                            {
                                <span class="text-black">
                                     Đã Thanh Toán
                                </span>
                            }
                            else
                            {
                                <span class="text-black">Trạng thái không xác định</span>
                            }
                        </td>
                        <td>
                            @if (@hoaDon.TrangThaiGiaoHang == (int)TrangThaiGiaoHang.DaGiaoHang)
                            {
                                <span class="text-black"> Đã giao hàng</span>
                            }
                            else if (@hoaDon.TrangThaiGiaoHang == (int)TrangThaiGiaoHang.DangGiaoHang)
                            {
                                <span class="text-black"> Đang giao hàng</span>
                            }
                            else if (@hoaDon.TrangThaiGiaoHang == (int)TrangThaiGiaoHang.ChoGiaoHang)
                            {
                                <span class="text-black"> Chờ giao hàng</span>
                            }
                            else if (@hoaDon.TrangThaiGiaoHang == (int)TrangThaiGiaoHang.ChoXacNhan)
                            {
                                <span class="text-black"> Chờ xác nhận</span>
                            }
                            else
                            {
                                <span class="text-black"> Đã hủy</span>
                            }
                        </td>
                        <td>@hoaDon.LiDoHuy</td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>Không có đơn hàng nào phù hợp với yêu cầu lọc.</p>
    }
</div>

WebApp/Views/HoaDon/ShowBill.cshtml
@using static Shop_Models.Heplers.TrangThai;

@{
    var httpContext = ViewContext.HttpContext;
    float thanhTien = 0;
    float thanhtiengiam = 0;
    float totaltiengiam = 0;
    float total = 0;
    float phaiTra = 0;
    var username = httpContext.Session.GetString("UserName");
}

<style>
    .custom-label {
        background-color: indianred; /* Màu nền */
        border: none; /* Không có viền */
        color: white; /* Màu chữ */
        padding: 15px 32px; /* Đệm trong */
        text-align: center; /* Canh giữa chữ */
        text-decoration: none; /* Không gạch chân */
        display: inline-block; /* Hiển thị như một khối nội tuyến */
        font-size: 16px; /* Kích thước chữ */
        margin: 4px 2px; /* Khoảng cách bên ngoài */
        cursor: pointer; /* Con trỏ chuột khi hover */
        border-radius: 4px; /* Bo góc */
    }

        .custom-label:hover {
            background-color: #45a049; /* Màu nền khi hover */
        }

</style>

<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Tra Cứu Đơn Hàng</h1>
                <nav class="d-flex align-items-center">
                    <a href="/Home">Home<span class="lnr lnr-arrow-right"></span></a>
                    <a href="/HoaDon/ShowBill">Tra Cứu Đơn Hàng</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->
<!--================Order Details Area =================-->
<section class="order_details section_gap">
    <div class="container">
        @if (username != null)
        {
            <a asp-controller="HoaDon" asp-action="GetCustomerPurchaseHistory" asp-route-customerId="@username" class="custom-label ">Lịch sử mua hàng</a>

        }

        <br />
        <br />
        <form asp-controller="HoaDon" asp-action="ShowBill" class="d-flex">
            <input class="form-control find-bill" name="invoiceCode" type="search" placeholder="Nhập mã hóa đơn để tìm kiếm" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">
                <i class="fa fa-search" aria-hidden="true"></i>
            </button>
        </form>
    </div>
    @if (ViewBag.Bill != null)
    {
        <div class="container">
            <h3 class="title_confirmation">
                Cảm ơn bạn. @if (ViewBag.Bill.TrangThaiGiaoHang == 0)
                {
                    <span> Đơn Hàng Của Bạn Đang Chờ xác nhận</span>
                }
                else if (ViewBag.Bill.TrangThaiGiaoHang == 1)
                {
                    <span> Đơn Hàng Của Bạn Đã Được Xác Nhận</span>
                }
                else if (ViewBag.Bill.TrangThaiGiaoHang == 2)
                {
                    <span> Đơn Hàng Của Bạn Đang Được Vận Chuyển</span>
                }
                else if (ViewBag.Bill.TrangThaiGiaoHang == 3)
                {
                    <span>  Đơn Hàng Của Bạn Đã Được Giao </span>
                }
                else if (ViewBag.Bill.TrangThaiGiaoHang == 4)
                {
                    <span> Đơn hàng đã bị hủy</span>
                }

                @*   @if (ViewBag.Bill.TrangThaiThanhToan == 3)
            {
            <span>Trạng thái thanh toán: Đã hoàn thành</span>
            }
            else if (ViewBag.Bill.TrangThaiThanhToan == 1)
            {
            <span>Trạng thái thanh toán: Chưa thanh toán</span>
            } *@
            </h3>
            <h4 class="title_confirmation">Thông tin đặt hàng</h4>

            <div class="row order_d_inner">
                <div class="col-lg-4">
                    <div class="details_item">

                        <ul class="list">
                            <li><a href="#"><span>Mã Hóa Đơn:</span> : @ViewBag.Bill.InvoiceCode</a></li>
                            <li><a href="#"><span>Tên Khách Hàng:</span> : @ViewBag.Bill.TenKhachHang</a></li>
                            <li><a href="#"><span>Số Điện Thoại:</span> : @ViewBag.Bill.PhoneNumber</a></li>
                            <li><a href="#"><span>Ngày Tạo:</span> : @ViewBag.Bill.CreateDate</a></li>
                            <li><a href="#"><span>Phương thức thanh toán:</span> : @ViewBag.Bill.Phuongthucthanhtoan</a></li>

                        </ul>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="details_item">
                        <ul class="list">
                            <li><a href="#"><span>Địa Chỉ Giao Hàng:</span> : @ViewBag.Bill.Address</a></li>
                            <li><a href="#"><span>Địa Chỉ Nhận Hàng</span> : @ViewBag.Bill.Address</a></li>
                            <li>
                                <a href="#">
                                    <span>Trạng thái thanh toán:</span> : @if (ViewBag.Bill.TrangThaiThanhToan == 1 && ViewBag.Bill.TrangThaiGiaoHang == 3)
                                    {
                                        <span> Đã hoàn thành</span>
                                    }
                                    else if (ViewBag.Bill.TrangThaiThanhToan == 1)
                                    {
                                        <span> Đã thanh toán</span>
                                    }
                                    else if (ViewBag.Bill.TrangThaiThanhToan == 0)
                                    {
                                        <span> Chưa thanh toán</span>
                                    }
                                </a>
                            </li>

                            @if (ViewBag.Bill.TrangThaiThanhToan == 1)
                            {
                                <li><a href="#"><span>Ngày Thanh Toán: </span> : @ViewBag.Bill.NgayThanhToan</a></li>

                            }
                            @* <li><a href="#"><span>Total</span> : @ViewBag.Bill.ThanhTien</a></li> *@
                            <li>
                                <a href="#">
                                    <span>Trạng Thái Giao Hàng </span> :  @if (ViewBag.Bill.TrangThaiGiaoHang == 0)
                                    {
                                        <span> Chờ xác nhận</span>
                                    }
                                    else if (ViewBag.Bill.TrangThaiGiaoHang == 1)
                                    {
                                        <span> Đã xác nhận</span>
                                    }
                                    else if (ViewBag.Bill.TrangThaiGiaoHang == 2)
                                    {
                                        <span> Đang vận chuyển</span>
                                    }
                                    else if (ViewBag.Bill.TrangThaiGiaoHang == 3)
                                    {
                                        <span> Đã giao</span>
                                    }
                                    else if (ViewBag.Bill.TrangThaiGiaoHang == 4)
                                    {
                                        <span> Đơn hàng đã bị hủy</span>
                                    }


                                </a>

                            </li>
                        </ul>
                    </div>
                </div>

            </div>
            <div class="order_details_table">
                <h2>Chi tiết đơn hàng</h2>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Mã Sản Phẩm</th>
                                <th scope="col">Màu Sắc</th>
                                <th scope="col">Số Lượng</th>
                                <th scope="col">Giá</th>
                                <th scope="col">Tổng</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var i in ViewBag.ListBillItem)
                            {
                                thanhTien = i.priceBan * i.quantity;
                                total += thanhTien;
                                thanhtiengiam = i.price * i.quantity;
                                totaltiengiam += thanhtiengiam;
                                <tr>
                                    <td>
                                        <p>@i.codeProductDetail</p>
                                    </td>
                                    <td>
                                        <p>@i.mauSac</p>
                                    </td>
                                    <td>
                                        <h5>@i.quantity</h5>
                                    </td>
                                    <td>
                                        <h5>@i.priceBan</h5>
                                    </td>
                                    <td>
                                        <p>@thanhTien</p>
                                    </td>
                                </tr>
                            }

                            <tr><td></td><td></td><td></td><td>Tổng thành tiền sản phẩm: @total</td></tr>
                            @if (totaltiengiam != total)
                            {
                                <tr><td></td><td></td><td></td><td>Tiền giảm giá sản phẩm: @(thanhtiengiam-thanhTien)</td></tr>
                            }
                            <tr><td></td><td></td><td>Giảm Giá Voucher: @ViewBag.Bill.GiamGia %</td><td>Quy Đổi Sang Tiền: @(total/100*ViewBag.Bill.GiamGia)</td></tr>
                            <tr><td></td><td></td><td>Phí Ship: @ViewBag.Bill.TienShip</td><td>Tổng tiền phải thanh toán: @ViewBag.Bill.ThanhTien</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    }


</section>