WebApp/Controllers/SanPhamChiTietController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using Shop_Models.Dto;
using Shop_Models.Entities;
using System.Data.SqlTypes;
using System.Drawing.Printing;
using System.Net.Http;

namespace WebApp.Controllers
{
    public class SanPhamChiTietController : Controller
    {
        private readonly ILogger<SanPhamChiTietController> _logger;
        private readonly IConfiguration _config;
        private readonly IHttpClientFactory _httpClientFactory;

        public SanPhamChiTietController(ILogger<SanPhamChiTietController> logger, IConfiguration config, IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
            _logger = logger;
            _config = config;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Details(string? sumguid)
        {

            //var client = _httpClientFactory.CreateClient("BeHat");

            //var lstRelatedProducts = await client.GetAsync($"/api/ChiTietSanPham/GetItemShopViewModelAsync?Id="+ sumguid);
            //if (lstRelatedProducts.IsSuccessStatusCode)
            //{
            //    var jsonResponse = await lstRelatedProducts.Content.ReadAsStringAsync();
            //    var respone = JsonConvert.DeserializeObject<ResponseDto>(jsonResponse);
            //    var content = JsonConvert.DeserializeObject<List<SPDanhSachViewModel>>(respone.Content.ToString());

            //    //var content2 = JsonConvert.DeserializeObject<List<SanPhamChiTietDto>>(jsonResponse.ToString());   
            //    var data = content.FirstOrDefault();
            //    return View(content);
            //}
            //return View();

            var client = _httpClientFactory.CreateClient("BeHat");

            var lstRelatedProducts = await client.GetAsync($"/api/ChiTietSanPham/GetItemDetailViewModelAynsc?Id=" + sumguid);
            if (lstRelatedProducts.IsSuccessStatusCode)
            {
                var jsonResponse = await lstRelatedProducts.Content.ReadAsStringAsync();
                var respone = JsonConvert.DeserializeObject<ResponseDto>(jsonResponse);
                var content = JsonConvert.DeserializeObject<ItemDetailViewModel>(respone.Content.ToString());
                ViewData["SumGuid"] = sumguid;
                //var content2 = JsonConvert.DeserializeObject<List<SanPhamChiTietDto>>(jsonResponse.ToString());   
                return View(content);
            }

            return View();


        }
        [HttpGet]
        public async Task<IActionResult> SanPhamDetailPatialView(string? sumguid)
        {
            //var client = _httpClientFactory.CreateClient("BeHat");

            //var lstRelatedProducts = await client.GetAsync($"/api/ChiTietSanPham/GetItemShopViewModelAsync?Id="+ sumguid);
            //if (lstRelatedProducts.IsSuccessStatusCode)
            //{
            //    var jsonResponse = await lstRelatedProducts.Content.ReadAsStringAsync();
            //    var respone = JsonConvert.DeserializeObject<ResponseDto>(jsonResponse);
            //    var content = JsonConvert.DeserializeObject<List<SPDanhSachViewModel>>(respone.Content.ToString());

            //    //var content2 = JsonConvert.DeserializeObject<List<SanPhamChiTietDto>>(jsonResponse.ToString());   
            //    var data = content.FirstOrDefault();
            //    return View(content);
            //}
            //return View();

            var client = _httpClientFactory.CreateClient("BeHat");

            var lstRelatedProducts = await client.GetAsync($"/api/ChiTietSanPham/GetItemDetailViewModelAynsc?Id=" + sumguid);

            var jsonResponse = await lstRelatedProducts.Content.ReadAsStringAsync();
            var respone = JsonConvert.DeserializeObject<ResponseDto>(jsonResponse);
            var content = JsonConvert.DeserializeObject<ItemDetailViewModel>(respone.Content.ToString());

            //var content2 = JsonConvert.DeserializeObject<List<SanPhamChiTietDto>>(jsonResponse.ToString());   
            return PartialView("/Views/SanPhamChiTiet/_SanPhamDetailPatialView.cshtml", content);


        }

        public async Task<IActionResult> GetItemDetailViewModelWhenSelectColor([FromQuery] string id, [FromQuery] string mauSac)
        {
            var client = _httpClientFactory.CreateClient("BeHat");
            var response = await client.GetStringAsync($"/api/ChiTietSanPham/Get-ItemDetailViewModel/{id}/{mauSac}");
            var content = JsonConvert.DeserializeObject<ItemDetailViewModel>(response.ToString());

            return Ok(content);
        }


        //[HttpPost]
        //public async Task<IActionResult> Details([FromBody] ParametersTongQuanDanhSach? parameters)
        //{

        //    var client = _httpClientFactory.CreateClient("BeHat");

        //    var lstRelatedProducts = await client.PostAsJsonAsync($"/api/ChiTietSanPham/GetFilteredDaTaDSTongQuanAynsc", parameters);
        //    if (lstRelatedProducts.IsSuccessStatusCode)
        //    {
        //        var jsonResponse = await lstRelatedProducts.Content.ReadAsStringAsync();
        //        var respone = JsonConvert.DeserializeObject<ResponseDto>(jsonResponse);
        //        var content = JsonConvert.DeserializeObject<List<SPDanhSachViewModel>>(respone.Content.ToString());

        //        //var content2 = JsonConvert.DeserializeObject<List<SanPhamChiTietDto>>(jsonResponse.ToString());
        //        var data = content.FirstOrDefault();
        //        return View(content);
        //    }
        //    return View();


        //}



        [HttpGet("GetRelatedProducts")]
        public async Task<IActionResult> GetRelatedProducts(string id)
        {
            var client = _httpClientFactory.CreateClient("BeHat");

            var lstRelatedProducts = await client.GetAsync($"/api/ChiTietSanPham/Get-List-RelatedProduct?sumGuild={id}");
            //ViewData["MauSac"] = new SelectList(lstRelatedProducts!.Select(x => x.TenMauSac).Distinct());
            //if (!string.IsNullOrEmpty(mauSac))
            //{
            //    ViewData["ValueMauSac"] = mauSac;
            //    lstRelatedProducts = lstRelatedProducts!.Where(it => it.TenMauSac!.ToLower() == mauSac.ToLower()).ToList();
            //}

            ViewBag.SumGuid = id;

            if (lstRelatedProducts.IsSuccessStatusCode)
            {
                var jsonResponse = await lstRelatedProducts.Content.ReadAsStringAsync();

                //var respone = JsonConvert.DeserializeObject<ResponseDto>(jsonResponse);
                var content = JsonConvert.DeserializeObject<List<SanPhamChiTietDto>>(jsonResponse.ToString());
                // Lấy số lượng bản ghi từ phản hồi và truyền nó qua ViewBag

                return PartialView("/Views/SanPhamChiTiet/_getRelatedProduct.cshtml", content!);
            }

            else
            {
                return StatusCode((int)lstRelatedProducts.StatusCode, lstRelatedProducts.ReasonPhrase);
            }
        }


        public async Task<IActionResult> GianHangAsync(int? page, int? pageSize, string? sorting, string? nameBrand, string? selectedCategory, string? selectedColor)
        {
            try
            {
                //ParameterGianHang parameter = new ParameterGianHang();
                //parameter.Page = 1;
                //parameter.PageSize = 6;
                if (page == null || pageSize == null)
                {
                    page = 1;
                    pageSize = 6;
                }
                ParameterGianHang parameter = new ParameterGianHang();
                parameter.Page = page;
                parameter.PageSize = pageSize;
                parameter.SortBy = sorting;
                parameter.TenThuongHieu = nameBrand;
                parameter.TenLoai = selectedCategory;
                parameter.TenMauSac = selectedColor;

                var client = _httpClientFactory.CreateClient("BeHat");
                var response = await client.PostAsJsonAsync("/api/ChiTietSanPham/GetItemShopGianHang", parameter);
                var responseMauSac = await client.GetStringAsync("/Get-All-MauSac");
                var responseThuongHieu = await client.GetStringAsync("/api/ThuongHieu");
                var responseLoai = await client.GetStringAsync("/api/Loai");
                if (response.IsSuccessStatusCode)
                {
                    var jsonResponseMauSac = responseMauSac.ToString();
                    var mausac = JsonConvert.DeserializeObject<List<MauSac>>(jsonResponseMauSac);
                  
                    var jsonResponseThuonghieu = responseThuongHieu.ToString();
                    var thuonghieu = JsonConvert.DeserializeObject<List<ThuongHieu>>(jsonResponseThuonghieu);
                    
                    var jsonResponseLoai = responseLoai.ToString();
                    var loai = JsonConvert.DeserializeObject<List<Loai>>(jsonResponseLoai);


                    var jsonResponse = await response.Content.ReadAsStringAsync();
                    var respone = JsonConvert.DeserializeObject<ResponseDto>(jsonResponse);
                    var content = JsonConvert.DeserializeObject<List<ItemShopViewModel>>(respone.Content.ToString());
                    // Lấy số lượng bản ghi từ phản hồi và truyền nó qua ViewBag
                    ViewBag.ListLoai = loai.ToList();
                    ViewBag.ListMau = mausac.ToList();
                    ViewBag.ListTH = thuonghieu.ToList();
                    ViewBag.TotalRecords = content.Count();
                    ViewBag.TotalPage = respone.PagingInfo.SoTrang;
                    ViewBag.CurrentPage = respone.PagingInfo.TrangHienTai;
                    return View();
                }

                else
                {
                    return StatusCode((int)response.StatusCode, response.ReasonPhrase);
                }

WebApp/Views/SanPhamChiTiet/_GianHangPartialView.cshtml
@using Shop_Models.Dto
@model List<ItemShopViewModel>
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration
@{
    var tongsobanghi = ViewBag.TotalRecords;
    var tongtrang = ViewBag.TotalPage;
    var tranghientai = ViewBag.CurrentPage;
}

@foreach (var item in Model)
{


    <div class="col-lg-4 col-md-6">
        <div class="single-product">
            @if (item.Anh != null && !string.IsNullOrEmpty(item.Anh))
            {
                @*                 <img style="max-height: 255px; max-width: 275px;" class="img-fluid" src="@Configuration.GetSection("UrlApiAdmin").Value@Url.Content(item.LinkAnh)" alt="">
        *@                <div class="product-m__thumb" data-id="@item.IdChiTietSp">

                    <a class="aspect aspect--bg-grey aspect--square u-d-block" onclick="fetchData2('@item.IdChiTietSp')">

                        <img class="aspect__img" style="height: 255.02px; width: 271.5px;" src="@Configuration.GetSection("UrlApiAdmin").Value@Url.Content(item.Anh)" alt="">
                    </a>
                </div>

            }
            else
            {@* <img class="img-fluid" src="~/behat-master/img/product/p1.jpg" alt=""> *@

                <div class="product-m__thumb" data-id="@item.IdChiTietSp" onclick="fetchData2('@item.IdChiTietSp')">

                    <a class="aspect aspect--bg-grey aspect--square u-d-block">

                        <img class="aspect__img" style="height: 255.02px; width: 271.5px;" src="~/behat-master/img/product/p9.jpg" alt="">
                    </a>
                </div>
            }

            <div class="product-details" id="postAPI" data-sumGuid="@item.IdChiTietSp" data-url="@Url.Action("GetRelatedProducts", "SanPhamChiTiet", new { sumGuid = item.IdChiTietSp })" @item.IdChiTietSp>
                <h6 onclick="fetchData2('@item.IdChiTietSp')">
                    [@item.MaSanPham] @item.TenSanPham @item.TheLoai
                </h6>
                <div class="price">
                    @* <h6>$150.00</h6>
                <h6 class="l-through">$210.00</h6> *@
                    @if (item.GiaBan == item.GiaGoc)
                    {
                        <div class="product-m__price" style="color: red">Giá: @string.Format(new System.Globalization.CultureInfo("vi-VN"), "{0:C0}", item.GiaBan)</div>

                    }
                    else
                    {
                        <div class="product-m__price" style="color: red">
                            Giá:
                            <span style="font-weight: bold">@string.Format(new System.Globalization.CultureInfo("vi-VN"), "{0:C0}", item.GiaBan)</span>
                            <del>@string.Format(new System.Globalization.CultureInfo("vi-VN"), "{0:C0}", item.GiaGoc)</del>
                        </div>
                    }
                    <span>Số lượng: @item.SoLuongTon</span>

                    <a href="@Url.Action("Details","SanPhamChiTiet", new {  sumguid=item.IdChiTietSp })" class="dropdown-item" style="color: orange;">Xem Mũ</a>

                </div>
                <div class="prd-bottom">
                    @* <a href="@Url.Action("AddProductToCart","Cart", new { codeProductDetail=item.MaSanPham })" class="social-info"> *@
                    <a href="#" class="social-info" onclick="addToCartBtn('@item.MaSanPham')">

                        <span class="ti-bag"></span>
                        <p class="hover-text">add to bag</p>
                    </a>
                    @* // Thêm sản phẩm vào danh sách sản phẩm yêu thích*@
                    <a href="#" class="social-info" onclick="addToFavoriteBtn('@item.IdChiTietSp')">
                        <span class="lnr lnr-heart"></span>
                        <p class="hover-text">Thêm vào yêu thích</p>
                    </a>
                   @*  <a href="" class="social-info">
                        <span class="lnr lnr-sync"></span>
                        <p class="hover-text">compare</p>
                    </a>
                    <a href="" class="social-info">
                        <span class="lnr lnr-move" id="btnFetchData2"></span>
                        <p class="hover-text">view more</p>
                    </a> *@
                </div>
            </div>
        </div>
    </div>
}


@*
@section Scripts{
    <script>
        function loadProductDetails(sumGuild) {
            console.log('Đang tải sản phẩm...');
            // Gửi yêu cầu AJAX để lấy dữ liệu sản phẩm
            $.ajax({
                url: '/SanPhamChiTiet/GetRelatedProducts',
                type: 'POST',
                data: { sumGuild: sumGuild },
                success: function (result) {
                    $('#productDetails').empty().html(result); // Cập nhật dữ liệu sản phẩm trong phần mới
                    $('#productDetailsModal').modal('show'); // Hiển thị modal với chi tiết sản phẩm
                },
                error: function (xhr, status, error) {
                    console.log(xhr.responseText);
                    console.log(status);
                    console.log(error);
                    console.log(xhr);
                }
            });
        }

        // // Khởi tạo DataTables cho bảng sản phẩm (nếu chưa được khởi tạo)
        // var table = $('#tables').DataTable();
        // if (!table || !$.fn.DataTable.isDataTable('#tables')) {
        //     $('#tables').DataTable({
        //         "paging": true,
        //         "lengthChange": true,
        //         "lengthMenu": [10, 25, 50, 75, 100],
        //         "searching": true
        //     });
        // }
    </script> *@



<script>
    // function addToCartBtn(codeProductDetail) {
    //     // var quantity = document.getElementById('sst').value;
    //     event.preventDefault(); // Chặn hành vi mặc định của form
    //     $.ajax({
    //         url: '/Cart/AddProductToCart',
    //         type: 'POST',
    //         data: { codeProductDetail: codeProductDetail },
    //         // contentType: false,
    //         // processData: false,
    //         success: function (results) {
    //             debugger
    //             console.log(results);
    //             // Hiển thị thông báo dựa trên kết quả từ server
    //             if (results.code === 200) {
    //                 debugger
    //                 console.log(results.message);
    //                 showNotification(results.message, "success");

    //             } else {
    //                 debugger
    //                 console.log(results.message);
    //                 showNotification(results.message, "error");

    //             }
    //         },
    //         error: function () {
    //             showNotification("Lỗi hệ thống", "error");
    //         }
    //     });
    // }
    function addToCartBtn(codeProductDetail) {
        // var quantity = document.getElementById('sst').value;
        event.preventDefault(); // Chặn hành vi mặc định của form
        $.ajax({
            url: '/Cart/AddProductToCart',
            type: 'POST',
            data: { codeProductDetail: codeProductDetail },
            // contentType: false,
            // processData: false,
            success: function (results) {
                debugger
                console.log(results);
                // Hiển thị thông báo dựa trên kết quả từ server
                if (results.code === 200) {
                    debugger
                    console.log(results.message);
                    showNotification(results.message, "success");

                } else {
                    debugger
                    console.log(results.message);
                    showNotification(results.message, "error");

                }
            },
            error: function () {
                showNotification("Lỗi hệ thống", "error");
            }
        });
    }
    function addToFavoriteBtn(productID) {
        // var quantity = document.getElementById('sst').value;
        debugger
        event.preventDefault(); // Chặn hành vi mặc định của form
        $.ajax({
            url: '/SanPhamYeuThich/UserAddProduct',
            type: 'POST',
            data: { productID: productID },
            // contentType: false,
            // processData: false,
            success: function (results) {
                debugger
                console.log(results);
                // Hiển thị thông báo dựa trên kết quả từ server
                // Hiển thị thông báo thêm vào thành công và ngược lại
                if (results.code === 200) {
                    debugger
                    console.log(results.message);
                    showNotification(results.message, "success");

                } else {
                    debugger
                    console.log(results.message);
                    showNotification(results.message, "error");

                }
            },
            error: function () {
                showNotification("Lỗi hệ thống", "error");
            }
        });
    }

    // Function hiển thị thông báo
    function showNotification(message, type) {
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "newestOnTop": true,
            "progressBar": true,
            "positionClass": "toast-bottom-right", // Sửa từ "toast-bot-right" thành "toast-bottom-right"
            "preventDuplicates": true,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        };

        // Hiển thị thông báo theo loại
        if (type === "success") {
            toastr.success(message);
        } else {
            toastr.error(message);
        }
    }


    $(document).ready(function () {

    });


</script>
}

WebApp/Views/SanPhamChiTiet/_SanPhamDetailPatialView.cshtml
@model Shop_Models.Dto.ItemDetailViewModel
@{
    ViewData["Title"] = "Details";

    int soluong = 0;
}
<div class="product_image_area" id="productDetail">
    <div class="container">
        <div class="row s_product_inner">
            <div class="col-lg-6">
                <div class="s_Product_carousel">
                    <div class="single-prd-item">
                        <img class="img-fluid" src="https://th.bing.com/th?id=OIP.QSzoNh2kpWRSf6ZWgLiA_QHaE6&w=306&h=203&c=8&rs=1&qlt=90&o=6&dpr=1.1&pid=3.1&rm=2" alt="">
                    </div>
                    <div class="single-prd-item">
                        <img class="img-fluid" src="https://th.bing.com/th?id=OIP.QSzoNh2kpWRSf6ZWgLiA_QHaE6&w=306&h=203&c=8&rs=1&qlt=90&o=6&dpr=1.1&pid=3.1&rm=2" alt="">
                    </div>
                    <div class="single-prd-item">
                        <img class="img-fluid" src="https://th.bing.com/th?id=OIP.QSzoNh2kpWRSf6ZWgLiA_QHaE6&w=306&h=203&c=8&rs=1&qlt=90&o=6&dpr=1.1&pid=3.1&rm=2" alt="">
                    </div>
                </div>

            </div>
            <div class="col-lg-5 offset-lg-1">
                <div class="s_product_text">
                    <h3>[@Model.MaSanPham]@Model.TenSanPham @Model.LoaiMu</h3>
                    @if (Model.GiaBan == Model.GiaKhuyenMai)
                    {
                        <h2>$ @Model.GiaBan</h2>
                    }
                    else
                    {
                        <h2>$ @Model.GiaKhuyenMai</h2>
                        <h4 class="l-through">$ @Model.GiaBan</h4>
                    }
                    <ul class="list">
                        <li><a @* class="active" *@ href="#"><span>Loại Mũ</span> : @Model.LoaiMu</a></li>
                        <li><a href="#"><span>Thương Hiệu</span> : @Model.ThuongHieu</a></li>
                        <li><a href="#"><span>Xuất Xứ</span> : @Model.XuatXu</a></li>
                        <li><a href="#"><span>Số Lượng</span> : @Model.SoLuongTon</a></li>
                    </ul>

                    <span class="pd-detail__label u-s-m-b-8">Màu sắc:</span>
                    <div class="pd-detail__color">
                        @foreach (var item in Model.itemShopListColor!)
                        {
                            if (Model.MauSac == item)
                            {
                                if (item == "white")
                                {
                                    <div class="color__radio">

                                        <input type="radio" id="@item" value="@item" name="color" checked>

                                        <label class="color__radio-label" for="@item" style="background-color: #8af0ff"></label>
                                    </div>
                                }
                                else
                                {
                                    <div class="color__radio">

                                        <input type="radio" id="@item" value="@item" name="color" checked>

                                        <label class="color__radio-label" for="@item" style="background-color: @item;  color:@item"></label>
                                    </div>
                                }

                            }
                            else
                            {
                                if (item == "white")
                                {
                                    <div class="color__radio">

                                        <input type="radio" id="@item" value="@item" name="color">

                                        <label class="color__radio-label" for="@item" style="background-color: #8af0ff"></label>
                                    </div>
                                }
                                else
                                {
                                    <div class="color__radio">

                                        <input type="radio" id="@item" value="@item" name="color">

                                        <label class="color__radio-label" for="@item" style="background-color: @item; color:@item"></label>
                                    </div>
                                }

                            }

                        }
                    </div>

                    <p>
                        Chiếc mũ mới nhất của chúng tôi sẽ làm bạn phải trầm trồ! Với thiết kế sáng tạo và chất liệu cao cấp,
                        chiếc mũ này không chỉ mang lại sự thoải mái mà còn là điểm nhấn hoàn hảo cho phong cách của bạn.
                        Khám phá ngay để trải nghiệm cảm giác ấm áp và phong cách tinh tế mà chiếc mũ mang lại!
                    </p>
                    <div class="product_count">
                        <label for="qty">Quantity:</label>
                        @* <input type="text" name="qty" id="sst" maxlength="12" value="@soluong" title="Quantity:" class="input-text qty" max="@soluong"> *@
                        <input type="number" name="qty" id="sst" maxlength="12" value="1" title="Quantity:" class="input-text qty">

                        <button onclick="increaseQuantity()"
                                class="increase items-count" type="button">
                            <i class="lnr lnr-chevron-up"></i>
                        </button>
                        <button onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst ) &amp;&amp; sst > 0 ) result.value--;return false;"
                                class="reduced items-count" type="button">
                            <i class="lnr lnr-chevron-down"></i>
                        </button>
                    </div>

                    <div class="card_area d-flex align-items-center">
                        @* <a class="primary-btn" href="@Url.Action("AddProductToCart","Cart", new {  codeProductDetail=Model.MaSanPham,soluong=  })">Add to Cart</a> *@
                        <a class="primary-btn" id="addToCartBtn" href="#">Add to Cart</a>
                        <a class="icon_btn" href="#"><i class="lnr lnr lnr-diamond"></i></a>
                        @* // Chức năng người dùng thêm sản phẩm vào danh sách yêu thích ở đây*@
                        <a class="icon_btn" href="#"><i class="lnr lnr lnr-heart"></i></a>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>
<script>
    // Lấy giá trị max từ mô hình
    const maxQuantity = parseInt("@Model.SoLuongTon", 10); // Chuyển đổi thành số nguyên

    // Lấy phần tử input
    var inputElement = document.getElementById('sst');

    // Cập nhật thuộc tính max của input
    inputElement.setAttribute('max', maxQuantity);

    // Đảm bảo giá trị nhập vào không vượt quá maxQuantity
    inputElement.addEventListener('input', function () {
        var value = inputElement.value;

        // Chỉ cho phép nhập số
        value = value.replace(/[^0-9]/g, '');

        // Chuyển giá trị thành số nguyên
        var intValue = parseInt(value);

        // Kiểm tra nếu giá trị nhập vào lớn hơn maxQuantity
        if (intValue > maxQuantity) {
            intValue = maxQuantity;
        }

        // Cập nhật lại giá trị input
        inputElement.value = isNaN(intValue) ? '' : intValue;
    });

    function increaseQuantity() {
        var value = parseInt(inputElement.value, 10);
        if (!isNaN(value)) {
            if (value < maxQuantity) {
                inputElement.value = value + 1;
            } else {
                inputElement.value = maxQuantity; // Nếu vượt quá số lượng tồn, giữ nguyên giá trị là số lượng tồn
            }
        }
    }

    function decreaseQuantity() {
        var value = parseInt(inputElement.value, 10);
        if (!isNaN(value) && value > 0) {
            inputElement.value = value - 1;
        }
    }

    document.getElementById('addToCartBtn').addEventListener('click', function () {
        var quantity = document.getElementById('sst').value;
        var codeProductDetail = '@Model.MaSanPham';
        var encodedCodeProductDetail = encodeURIComponent(codeProductDetail);
        var url = '@Url.Action("AddProductToCart", "Cart")';
        url += '?codeProductDetail=' + encodedCodeProductDetail + '&soluong=' + quantity;
        window.location.href = url;
    });
</script>




<style>
    .l-through {
        text-decoration: line-through;
    }
</style>
<style>
    .pd-detail__color {
        display: flex;
        flex-wrap: wrap;
    }

    .color__radio {
        margin-right: 10px;
    }

        .color__radio input[type=radio] {
            display: none;
        }

        .color__radio label {
            display: inline-block;
            width: 30px;
            height: 30px;
            border: 2px solid transparent; /* Border ban đầu */
            border-radius: 50%; /* Đảm bảo hình tròn */
            cursor: pointer;
            margin-bottom: 5px;
        }

        .color__radio input[type=radio]:checked + label {
            border-color: #333; /* Màu border khi được chọn */
        }
</style>