AdminApp/Controllers/MauSacController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Shop_Models.Entities;
using System.Text;


namespace AdminApp.Controllers
{
    public class MauSacController : Controller
    {
        // GET: HomeController1
        public HttpClient httpClient { get; set; }
        public MauSacController(HttpClient httpClient)
        {
            this.httpClient = httpClient;
        }

        public IActionResult Index()
        {
            var accessToken = HttpContext.Session.GetString("AccessToken");
            var accessRole = HttpContext.Session.GetString("Result");
            if (!string.IsNullOrEmpty(accessToken) && accessRole == "Admin" || !string.IsNullOrEmpty(accessToken) && accessRole == "NhanVien")
            {
                return View();
            }
            else
            {

                return RedirectToAction("Login", "Home");
            }
            //return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }


        public async Task<IActionResult> GetAll()
        {


            var accessToken = HttpContext.Session.GetString("AccessToken");
            var accessRole = HttpContext.Session.GetString("Result");
            if (!string.IsNullOrEmpty(accessToken) && accessRole == "Admin" || !string.IsNullOrEmpty(accessToken) && accessRole == "NhanVien")
            {
                var url = $"https://localhost:7050/Get-All-MauSac";
                var response = await httpClient.GetAsync(url);
                var apiData = await response.Content.ReadAsStringAsync();
                var a = JsonConvert.DeserializeObject<List<MauSac>>(apiData);
                return View(a);
            }
            else
            {

                return RedirectToAction("Login", "Home");
            }

        }

        // GET: HomeController1/Details/5
        [HttpGet]
        public IActionResult Create()
        {


            var accessToken = HttpContext.Session.GetString("AccessToken");
            var accessRole = HttpContext.Session.GetString("Result");
            if (!string.IsNullOrEmpty(accessToken) && accessRole == "Admin" || !string.IsNullOrEmpty(accessToken) && accessRole == "NhanVien")
            {
                return View();
            }
            else
            {

                return RedirectToAction("Login", "Home");
            }


        }
        [HttpPost]
        public async Task<IActionResult> Create(MauSac a)
        {


            var accessToken = HttpContext.Session.GetString("AccessToken");
            var accessRole = HttpContext.Session.GetString("Result");
            if (!string.IsNullOrEmpty(accessToken) && accessRole == "Admin" || !string.IsNullOrEmpty(accessToken) && accessRole == "NhanVien")
            {
                var url = $"https://localhost:7050/Create-MauSac?MaMau={a.MaMauSac}&tenMau={a.TenMauSac}&TrangThai={a.TrangThai}";
                var response = await httpClient.PostAsync(url, null);
                if (response.IsSuccessStatusCode)
                    return RedirectToAction("GetAll");
                return View();
            }
            else
            {

                return RedirectToAction("Login", "Home");
            }

        }



        public async Task<IActionResult> DetailMauSac(Guid a)
        {



            var accessToken = HttpContext.Session.GetString("AccessToken");
            var accessRole = HttpContext.Session.GetString("Result");
            if (!string.IsNullOrEmpty(accessToken) && accessRole == "Admin" || !string.IsNullOrEmpty(accessToken) && accessRole == "NhanVien")
            {
                var url = $"https://localhost:7050/Get-MauSac?a={a}";
                var response = await httpClient.GetAsync(url);
                var apiData = await response.Content.ReadAsStringAsync();
                var MS = JsonConvert.DeserializeObject<MauSac>(apiData);
                return View(MS);
            }
            else
            {

                return RedirectToAction("Login", "Home");
            }

        }


        // GET: HomeController1/Edit/5
        [HttpGet]
        public async Task<IActionResult> EditMauSac(Guid id)
        {


            var accessToken = HttpContext.Session.GetString("AccessToken");
            var accessRole = HttpContext.Session.GetString("Result");
            if (!string.IsNullOrEmpty(accessToken) && accessRole == "Admin" || !string.IsNullOrEmpty(accessToken) && accessRole == "NhanVien")
            {
                var url = $"https://localhost:7050/Get-All-MauSac";
                var response = await httpClient.GetAsync(url);
                var apiData = await response.Content.ReadAsStringAsync();
                var MS = JsonConvert.DeserializeObject<List<MauSac>>(apiData).FirstOrDefault(x => x.Guid == id);
                return View(MS);
            }
            else
            {

                return RedirectToAction("Login", "Home");
            }

        }

        [HttpPost]
        public async Task<IActionResult> EditMauSac(MauSac a)
        {



            var accessToken = HttpContext.Session.GetString("AccessToken");
            var accessRole = HttpContext.Session.GetString("Result");
            if (!string.IsNullOrEmpty(accessToken) && accessRole == "Admin" || !string.IsNullOrEmpty(accessToken) && accessRole == "NhanVien")
            {
                var url = $"https://localhost:7050/Update-MS?id={a.Guid}&MaMau={a.MaMauSac}&tenMau={a.TenMauSac}&TrangThai={a.TrangThai}";
                var response = await httpClient.PostAsync(url, null);
                if (response.IsSuccessStatusCode)
                    return RedirectToAction("GetAll");

                return View();
            }
            else
            {

                return RedirectToAction("Login", "Home");
            }

        }



        // GET: HomeController1/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {
            var url = $"https://localhost:7050/delete-MS?id={id}";
            var response = await httpClient.DeleteAsync(url);

            if (response.IsSuccessStatusCode)
                return RedirectToAction("GetAll");

            return View();
        }


    }
}

AdminApp/Views/MauSac/Create.cshtml
@model Shop_Models.Entities.MauSac

@{
    ViewData["Title"] = "CreateMauSac";
}

<h1>CreateMauSac</h1>

<h4>MauSac</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="MaMauSac" class="control-label"></label>
                <input asp-for="MaMauSac" class="form-control" />
                <span asp-validation-for="MaMauSac" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenMauSac" class="control-label"></label>
                <input asp-for="TenMauSac" class="form-control" />
                <span asp-validation-for="TenMauSac" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrangThai" class="control-label"></label>
                <input asp-for="TrangThai" class="form-control" />
                <span asp-validation-for="TrangThai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="GetAll">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AdminApp/Views/MauSac/CreateMauSac.cshtml
@model Shop_Models.Entities.MauSac

@{
    ViewData["Title"] = "CreateMauSac";
}

<h1>CreateMauSac</h1>

<h4>MauSac</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateMauSac">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="MaMauSac" class="control-label"></label>
                <input asp-for="MaMauSac" class="form-control" />
                <span asp-validation-for="MaMauSac" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenMauSac" class="control-label"></label>
                <input asp-for="TenMauSac" class="form-control" />
                <span asp-validation-for="TenMauSac" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrangThai" class="control-label"></label>
                <input asp-for="TrangThai" class="form-control" />
                <span asp-validation-for="TrangThai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="GetAllMauSac">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AdminApp/Views/MauSac/DetailMauSac.cshtml
@model Shop_Models.Entities.MauSac

@{
    ViewData["Title"] = "DetailMauSac";
}

<h1>DetailMauSac</h1>

<div>
    <h4>MauSac</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Guid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Guid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaMauSac)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaMauSac)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenMauSac)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenMauSac)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrangThai)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "EditMauSac", new {  id = Model.Guid  }) |
    <a asp-action="GetAllMauSac">Back to List</a>
</div>

AdminApp/Views/MauSac/EditMauSac.cshtml
@model Shop_Models.Entities.MauSac

@{
    ViewData["Title"] = "EditMauSac";
}

<h1>Chỉnh Sửa Màu Sắc</h1>

<hr />
<div class="row">
    <div class="col-md-6 offset-md-3">
        <form asp-action="EditMauSac">
            <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>

            <div class="form-group">
                <label asp-for="Guid" class="control-label"></label>
                <input asp-for="Guid" class="form-control" />
                <span asp-validation-for="Guid" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="MaMauSac" class="control-label"></label>
                <input asp-for="MaMauSac" class="form-control" />
                <span asp-validation-for="MaMauSac" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TenMauSac" class="control-label"></label>
                <input asp-for="TenMauSac" class="form-control" />
                <span asp-validation-for="TenMauSac" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TrangThai" class="control-label"></label>
                <select asp-for="TrangThai" class="form-control">
                    <option value="">-- Chọn trạng thái --</option>
                    <option value="1">Hoạt động</option>
                    <option value="0">Không hoạt động</option>
                </select>
                <span asp-validation-for="TrangThai" class="text-danger"></span>
            </div>

            <div class="form-group text-center">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="text-center mt-3">
    <a asp-action="GetAll" class="btn btn-secondary">Back to List</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AdminApp/Views/MauSac/GetAll.cshtml
@using static Shop_Models.Heplers.TrangThai;
@model IEnumerable<Shop_Models.Entities.MauSac>
@{
    ViewData["Title"] = "GetAllMauSac";
}

<style>
    .card {
        border: 1px solid #ddd;
        border-radius: 5px;
        padding: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        overflow: auto;
    }
    .form-container {
        display: none; /* Ẩn form ban đầu */
    }
</style>

<div class="container">
    <div class="row">
        <h1>Quản Lý Màu Sắc</h1>
        <div class="col-md-8">
            <div class="card" style="height: 430px;">
                <div class="card-body">
                    <div class="table-responsive" id="tableContainer">
                        <table class="table" id="loaiTable">
                            <thead>
                                <tr>
                                    <th>Mã Màu Sắc</th>
                                    <th>Tên Màu Sắc</th>
                                    <th>Trạng Thái</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.MaMauSac)</td>
                                        <td>@Html.DisplayFor(modelItem => item.TenMauSac)</td>
                                        <td>
                                            @if (item.TrangThai == (int)TrangThaiCoBan.HoatDong)
                                            {
                                                <span class="text-black">Hoạt Động</span>
                                            }
                                            else if (item.TrangThai == (int)TrangThaiCoBan.KhongHoatDong)
                                            {
                                                <span class="text-black">Không Hoạt Động</span>
                                            }
                                            else
                                            {
                                                <span class="text-black">Trạng thái không xác định</span>
                                            }
                                        </td>
                                        <td>
                                            <button class="btn btn-primary edit-btn" data-id="@item.Guid" data-ma="@item.MaMauSac" data-ten="@item.TenMauSac" data-trangthai="@item.TrangThai" title="Sửa"><i class="bx bxs-edit"></i></button>
                                            <a asp-area="" asp-controller="MauSac" asp-action="Delete" asp-route-id="@item.Guid" class="btn btn-danger" onclick="return confirm('Bạn chắc chắn có muốn xóa?')" title="Xóa"><i class="bx bxs-trash-alt"></i></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <button class="btn btn-success" id="showAddFormBtn">Thêm màu sắc mới</button>
            <div class="card form-container" id="addFormContainer">
                <div class="card-body">
                    <h2 class="card-title">Thêm màu sắc mới</h2>
                    <form id="createMauSacForm" asp-action="Create" method="post">
                        <div class="form-group">
                            <label for="maMauSac">Mã màu sắc:</label>
                            <input type="text" class="form-control" id="maMauSac" name="MaMauSac" />
                        </div>
                        <div class="form-group">
                            <label for="tenMauSac">Tên màu sắc:</label>
                            <input type="text" class="form-control" id="tenMauSac" name="TenMauSac" />
                        </div>
                        <div class="form-group">
                            <label for="Trangthai">Trạng Thái :</label>
                            <select class="form-control" id="Trangthai" name="Trangthai">
                                <option value="">-- Chọn trạng thái --</option>
                                <option value="1">Hoạt động</option>
                                <option value="0">Không hoạt động</option>
                            </select>
                        </div>
                        <div class="text-center mt-3">
                            <button type="button" onclick="kiemTraTrungMa()" class="btn btn-success">Thêm</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card form-container mt-3" id="editFormContainer">
                <div class="card-body">
                    <h2 class="card-title">Chỉnh sửa màu sắc</h2>
                    <form id="editMauSacForm" asp-action="EditMauSac" method="post">
                        <input type="hidden" id="editGuid" name="Guid" />
                        <div class="form-group">
                            <label for="editMaMauSac">Mã màu sắc:</label>
                            <input type="text" class="form-control" id="editMaMauSac" name="MaMauSac" />
                        </div>
                        <div class="form-group">
                            <label for="editTenMauSac">Tên màu sắc:</label>
                            <input type="text" class="form-control" id="editTenMauSac" name="TenMauSac" />
                        </div>
                        <div class="form-group">
                            <label for="editTrangthai">Trạng Thái :</label>
                            <select class="form-control" id="editTrangthai" name="Trangthai">
                                <option value="">-- Chọn trạng thái --</option>
                                <option value="1">Hoạt động</option>
                                <option value="0">Không hoạt động</option>
                            </select>
                        </div>
                        <div class="text-center mt-3">
                            <button type="submit" class="btn btn-primary">Cập nhật</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Thư viện DataTables CSS -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">

<!-- Thư viện jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!-- Thư viện DataTables JavaScript -->
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>

<!-- Thư viện No Pagination UI -->
<script src="https://cdn.datatables.net/1.11.5/js/dataTables.jqueryui.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/dataTables.jqueryui.min.css">
<script>
    function kiemTraTrungMa() {
        var maMauSac = document.getElementById("maMauSac").value;
        var maLoaiDaHienThi = [];

        $("#loaiTable tbody tr").each(function () {
            maLoaiDaHienThi.push($(this).find("td:first").text().trim());
        });

        if (maLoaiDaHienThi.includes(maMauSac)) {
            alert("Mã đã tồn tại trong dữ liệu. Vui lòng chọn mã khác.");
        } else {
            $("#createMauSacForm").submit();
        }
    }

    $(document).ready(function () {
        var table = $('#THTable').DataTable();
        if (!table || !$.fn.DataTable.isDataTable('#THTable')) {
            // Nếu bảng chưa được khởi tạo DataTables thì khởi tạo nó
            $('#THTable').DataTable({
                "scrollY": "250px", // Chiều cao của khu vực lướt
                "paging": true, // Hiển thị chia trang
                "pagingType": "simple_numbers", // Loại chia trang (không có ô vuông nhỏ)
                "lengthMenu": [5, 15, 25, 50], // Lựa chọn số lượng hàng trên mỗi trang
                "renderer": "jqueryui" // Sử dụng renderer của jQuery UI
            });
        }

        $("#createMauSacForm button").click(kiemTraTrungMa);

        $(".edit-btn").click(function () {
            var guid = $(this).data("id");
            var maMauSac = $(this).data("ma");
            var tenMauSac = $(this).data("ten");
            var trangthai = $(this).data("trangthai");

            $("#editGuid").val(guid);
            $("#editMaMauSac").val(maMauSac);
            $("#editTenMauSac").val(tenMauSac);
            $("#editTrangthai").val(trangthai);

            $("#editFormContainer").show();
            $("#addFormContainer").hide();
        });

        $("#showAddFormBtn").click(function() {
            $("#addFormContainer").show();
            $("#editFormContainer").hide();
        });
    });
</script>

AdminApp/Views/MauSac/GetAllMauSac.cshtml
@model IEnumerable<Shop_Models.Entities.MauSac>

@{
    ViewData["Title"] = "GetAllMauSac";
}

<h1>GetAllMauSac</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Guid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaMauSac)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TenMauSac)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TrangThai)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Guid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaMauSac)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenMauSac)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TrangThai)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditMauSac", new {  id=item.Guid  }) |
                @Html.ActionLink("Details", "DeleteMauSac", new {  id=item.Guid  }) |
                @Html.ActionLink("Delete", "DeleteMauSac", new {  id=item.Guid  })
            </td>
        </tr>
}
    </tbody>
</table>